// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKnzBini71T94xJ8umDEsfmFoiPNLFaE',
    appId: '1:614519166179:web:0b9ff0a157efd5a1e661d6',
    messagingSenderId: '614519166179',
    projectId: 'tourney-craft',
    authDomain: 'tourney-craft.firebaseapp.com',
    storageBucket: 'tourney-craft.appspot.com',
    measurementId: 'G-XFFB95PCX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHfRinDGUaz24SW8Zp0IOw36U1_JxcjHk',
    appId: '1:614519166179:android:79062a6ad7cf115be661d6',
    messagingSenderId: '614519166179',
    projectId: 'tourney-craft',
    storageBucket: 'tourney-craft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3MXYRZArzrl8Q3-xYB_1svb9Z_BBEbQ',
    appId: '1:614519166179:ios:adaea9ddf0229300e661d6',
    messagingSenderId: '614519166179',
    projectId: 'tourney-craft',
    storageBucket: 'tourney-craft.appspot.com',
    iosBundleId: 'br.com.zamuelfernandes.tourneyCraft',
  );
}
